name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Gradle Build Action
    # You may pin to the exact commit or the version.
    # uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef
      uses: gradle/gradle-build-action@v2.3.3
      with:
        # Gradle version to use
        gradle-version: 7.2
    - name: Build with Gradle
      run: gradle build
      working-directory: MovieJunkie-Backend
