name: Java CI with Gradle

env: 
  APP_PATH: ./src/main/resources/application.properties

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: moviejunkie
          POSTGRES_PASSWORD: password
          POSTGRES_USER: spring
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Create application.properties file
      run : |
        ls -la
        rm -rf $APP_PATH
        ls -la
        echo "server.port=${{ '${PORT:8080}' }}" >> ${{ env.APP_PATH }}
        echo "spring.datasource.driver-class-name=org.postgresql.Driver" >> ${{ env.APP_PATH }}
        echo "spring.datasource.url=jdbc:postgresql://localhost:5432/moviejunkie" >> ${{ env.APP_PATH }}
        echo "spring.datasource.username=spring" >> ${{ env.APP_PATH }}
        echo "spring.datasource.password=password" >> ${{ env.APP_PATH }}
        echo "spring.jpa.hibernate.ddl-auto=create" >> ${{ env.APP_PATH }}
        echo "spring.jpa.show-sql=true" >> ${{ env.APP_PATH }}
        echo "spring.jpa.properties.hibernate.format_sql=true" >> ${{ env.APP_PATH }}
        echo "spring.jpa.database-platform=org.hibernate.dialect.PostgresSQLDialect" >> ${{ env.APP_PATH }}
        echo "server.error.include-message=always" >> ${{ env.APP_PATH }}
        echo "tmdb.apikey=f4a943efca00a3cd96ac56ff8ad1ea3c" >> ${{ env.APP_PATH }}
        ls -la
        chmod a+x ${{ env.APP_PATH }}
        ls -la ./src/main/resources
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Add permission
      run: chmod +x gradlew
    - name: Build test
      run: ./gradlew clean test
