name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: MovieJunkie-Backend
    - name: Build with Gradle
      run: ./gradlew build
